// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eraftpb.proto

#ifndef PROTOBUF_INCLUDED_eraftpb_2eproto
#define PROTOBUF_INCLUDED_eraftpb_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_eraftpb_2eproto 

namespace protobuf_eraftpb_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[7];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_eraftpb_2eproto
namespace eraftpb {
class ConfChange;
class ConfChangeDefaultTypeInternal;
extern ConfChangeDefaultTypeInternal _ConfChange_default_instance_;
class ConfState;
class ConfStateDefaultTypeInternal;
extern ConfStateDefaultTypeInternal _ConfState_default_instance_;
class Entry;
class EntryDefaultTypeInternal;
extern EntryDefaultTypeInternal _Entry_default_instance_;
class HardState;
class HardStateDefaultTypeInternal;
extern HardStateDefaultTypeInternal _HardState_default_instance_;
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
class Snapshot;
class SnapshotDefaultTypeInternal;
extern SnapshotDefaultTypeInternal _Snapshot_default_instance_;
class SnapshotMetadata;
class SnapshotMetadataDefaultTypeInternal;
extern SnapshotMetadataDefaultTypeInternal _SnapshotMetadata_default_instance_;
}  // namespace eraftpb
namespace google {
namespace protobuf {
template<> ::eraftpb::ConfChange* Arena::CreateMaybeMessage<::eraftpb::ConfChange>(Arena*);
template<> ::eraftpb::ConfState* Arena::CreateMaybeMessage<::eraftpb::ConfState>(Arena*);
template<> ::eraftpb::Entry* Arena::CreateMaybeMessage<::eraftpb::Entry>(Arena*);
template<> ::eraftpb::HardState* Arena::CreateMaybeMessage<::eraftpb::HardState>(Arena*);
template<> ::eraftpb::Message* Arena::CreateMaybeMessage<::eraftpb::Message>(Arena*);
template<> ::eraftpb::Snapshot* Arena::CreateMaybeMessage<::eraftpb::Snapshot>(Arena*);
template<> ::eraftpb::SnapshotMetadata* Arena::CreateMaybeMessage<::eraftpb::SnapshotMetadata>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace eraftpb {

enum EntryType {
  EntryNormal = 0,
  EntryConfChange = 1,
  EntryType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  EntryType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool EntryType_IsValid(int value);
const EntryType EntryType_MIN = EntryNormal;
const EntryType EntryType_MAX = EntryConfChange;
const int EntryType_ARRAYSIZE = EntryType_MAX + 1;

const ::google::protobuf::EnumDescriptor* EntryType_descriptor();
inline const ::std::string& EntryType_Name(EntryType value) {
  return ::google::protobuf::internal::NameOfEnum(
    EntryType_descriptor(), value);
}
inline bool EntryType_Parse(
    const ::std::string& name, EntryType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EntryType>(
    EntryType_descriptor(), name, value);
}
enum MessageType {
  MsgHup = 0,
  MsgBeat = 1,
  MsgPropose = 2,
  MsgAppend = 3,
  MsgAppendResponse = 4,
  MsgRequestVote = 5,
  MsgRequestVoteResponse = 6,
  MsgSnapshot = 7,
  MsgHeartbeat = 8,
  MsgHeartbeatResponse = 9,
  MsgUnreachable = 10,
  MsgSnapStatus = 11,
  MsgCheckQuorum = 12,
  MsgTransferLeader = 13,
  MsgTimeoutNow = 14,
  MsgReadIndex = 15,
  MsgReadIndexResp = 16,
  MsgRequestPreVote = 17,
  MsgRequestPreVoteResponse = 18,
  MessageType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  MessageType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool MessageType_IsValid(int value);
const MessageType MessageType_MIN = MsgHup;
const MessageType MessageType_MAX = MsgRequestPreVoteResponse;
const int MessageType_ARRAYSIZE = MessageType_MAX + 1;

const ::google::protobuf::EnumDescriptor* MessageType_descriptor();
inline const ::std::string& MessageType_Name(MessageType value) {
  return ::google::protobuf::internal::NameOfEnum(
    MessageType_descriptor(), value);
}
inline bool MessageType_Parse(
    const ::std::string& name, MessageType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MessageType>(
    MessageType_descriptor(), name, value);
}
enum ConfChangeType {
  AddNode = 0,
  RemoveNode = 1,
  AddLearnerNode = 2,
  ConfChangeType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ConfChangeType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ConfChangeType_IsValid(int value);
const ConfChangeType ConfChangeType_MIN = AddNode;
const ConfChangeType ConfChangeType_MAX = AddLearnerNode;
const int ConfChangeType_ARRAYSIZE = ConfChangeType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ConfChangeType_descriptor();
inline const ::std::string& ConfChangeType_Name(ConfChangeType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ConfChangeType_descriptor(), value);
}
inline bool ConfChangeType_Parse(
    const ::std::string& name, ConfChangeType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ConfChangeType>(
    ConfChangeType_descriptor(), name, value);
}
// ===================================================================

class Entry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eraftpb.Entry) */ {
 public:
  Entry();
  virtual ~Entry();

  Entry(const Entry& from);

  inline Entry& operator=(const Entry& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Entry(Entry&& from) noexcept
    : Entry() {
    *this = ::std::move(from);
  }

  inline Entry& operator=(Entry&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Entry& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Entry* internal_default_instance() {
    return reinterpret_cast<const Entry*>(
               &_Entry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Entry* other);
  friend void swap(Entry& a, Entry& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Entry* New() const final {
    return CreateMaybeMessage<Entry>(NULL);
  }

  Entry* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Entry>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Entry& from);
  void MergeFrom(const Entry& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Entry* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes data = 4;
  void clear_data();
  static const int kDataFieldNumber = 4;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // bytes context = 6;
  void clear_context();
  static const int kContextFieldNumber = 6;
  const ::std::string& context() const;
  void set_context(const ::std::string& value);
  #if LANG_CXX11
  void set_context(::std::string&& value);
  #endif
  void set_context(const char* value);
  void set_context(const void* value, size_t size);
  ::std::string* mutable_context();
  ::std::string* release_context();
  void set_allocated_context(::std::string* context);

  // uint64 term = 2;
  void clear_term();
  static const int kTermFieldNumber = 2;
  ::google::protobuf::uint64 term() const;
  void set_term(::google::protobuf::uint64 value);

  // uint64 index = 3;
  void clear_index();
  static const int kIndexFieldNumber = 3;
  ::google::protobuf::uint64 index() const;
  void set_index(::google::protobuf::uint64 value);

  // .eraftpb.EntryType entry_type = 1;
  void clear_entry_type();
  static const int kEntryTypeFieldNumber = 1;
  ::eraftpb::EntryType entry_type() const;
  void set_entry_type(::eraftpb::EntryType value);

  // bool sync_log = 5;
  void clear_sync_log();
  static const int kSyncLogFieldNumber = 5;
  bool sync_log() const;
  void set_sync_log(bool value);

  // @@protoc_insertion_point(class_scope:eraftpb.Entry)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::google::protobuf::internal::ArenaStringPtr context_;
  ::google::protobuf::uint64 term_;
  ::google::protobuf::uint64 index_;
  int entry_type_;
  bool sync_log_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_eraftpb_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SnapshotMetadata : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eraftpb.SnapshotMetadata) */ {
 public:
  SnapshotMetadata();
  virtual ~SnapshotMetadata();

  SnapshotMetadata(const SnapshotMetadata& from);

  inline SnapshotMetadata& operator=(const SnapshotMetadata& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SnapshotMetadata(SnapshotMetadata&& from) noexcept
    : SnapshotMetadata() {
    *this = ::std::move(from);
  }

  inline SnapshotMetadata& operator=(SnapshotMetadata&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SnapshotMetadata& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SnapshotMetadata* internal_default_instance() {
    return reinterpret_cast<const SnapshotMetadata*>(
               &_SnapshotMetadata_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(SnapshotMetadata* other);
  friend void swap(SnapshotMetadata& a, SnapshotMetadata& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SnapshotMetadata* New() const final {
    return CreateMaybeMessage<SnapshotMetadata>(NULL);
  }

  SnapshotMetadata* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SnapshotMetadata>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SnapshotMetadata& from);
  void MergeFrom(const SnapshotMetadata& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SnapshotMetadata* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .eraftpb.ConfState conf_state = 1;
  bool has_conf_state() const;
  void clear_conf_state();
  static const int kConfStateFieldNumber = 1;
  private:
  const ::eraftpb::ConfState& _internal_conf_state() const;
  public:
  const ::eraftpb::ConfState& conf_state() const;
  ::eraftpb::ConfState* release_conf_state();
  ::eraftpb::ConfState* mutable_conf_state();
  void set_allocated_conf_state(::eraftpb::ConfState* conf_state);

  // uint64 index = 2;
  void clear_index();
  static const int kIndexFieldNumber = 2;
  ::google::protobuf::uint64 index() const;
  void set_index(::google::protobuf::uint64 value);

  // uint64 term = 3;
  void clear_term();
  static const int kTermFieldNumber = 3;
  ::google::protobuf::uint64 term() const;
  void set_term(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:eraftpb.SnapshotMetadata)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::eraftpb::ConfState* conf_state_;
  ::google::protobuf::uint64 index_;
  ::google::protobuf::uint64 term_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_eraftpb_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Snapshot : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eraftpb.Snapshot) */ {
 public:
  Snapshot();
  virtual ~Snapshot();

  Snapshot(const Snapshot& from);

  inline Snapshot& operator=(const Snapshot& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Snapshot(Snapshot&& from) noexcept
    : Snapshot() {
    *this = ::std::move(from);
  }

  inline Snapshot& operator=(Snapshot&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Snapshot& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Snapshot* internal_default_instance() {
    return reinterpret_cast<const Snapshot*>(
               &_Snapshot_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Snapshot* other);
  friend void swap(Snapshot& a, Snapshot& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Snapshot* New() const final {
    return CreateMaybeMessage<Snapshot>(NULL);
  }

  Snapshot* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Snapshot>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Snapshot& from);
  void MergeFrom(const Snapshot& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Snapshot* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes data = 1;
  void clear_data();
  static const int kDataFieldNumber = 1;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // .eraftpb.SnapshotMetadata metadata = 2;
  bool has_metadata() const;
  void clear_metadata();
  static const int kMetadataFieldNumber = 2;
  private:
  const ::eraftpb::SnapshotMetadata& _internal_metadata() const;
  public:
  const ::eraftpb::SnapshotMetadata& metadata() const;
  ::eraftpb::SnapshotMetadata* release_metadata();
  ::eraftpb::SnapshotMetadata* mutable_metadata();
  void set_allocated_metadata(::eraftpb::SnapshotMetadata* metadata);

  // @@protoc_insertion_point(class_scope:eraftpb.Snapshot)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::eraftpb::SnapshotMetadata* metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_eraftpb_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Message : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eraftpb.Message) */ {
 public:
  Message();
  virtual ~Message();

  Message(const Message& from);

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Message(Message&& from) noexcept
    : Message() {
    *this = ::std::move(from);
  }

  inline Message& operator=(Message&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Message& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(Message* other);
  friend void swap(Message& a, Message& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Message* New() const final {
    return CreateMaybeMessage<Message>(NULL);
  }

  Message* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Message>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Message* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .eraftpb.Entry entries = 7;
  int entries_size() const;
  void clear_entries();
  static const int kEntriesFieldNumber = 7;
  ::eraftpb::Entry* mutable_entries(int index);
  ::google::protobuf::RepeatedPtrField< ::eraftpb::Entry >*
      mutable_entries();
  const ::eraftpb::Entry& entries(int index) const;
  ::eraftpb::Entry* add_entries();
  const ::google::protobuf::RepeatedPtrField< ::eraftpb::Entry >&
      entries() const;

  // bytes context = 12;
  void clear_context();
  static const int kContextFieldNumber = 12;
  const ::std::string& context() const;
  void set_context(const ::std::string& value);
  #if LANG_CXX11
  void set_context(::std::string&& value);
  #endif
  void set_context(const char* value);
  void set_context(const void* value, size_t size);
  ::std::string* mutable_context();
  ::std::string* release_context();
  void set_allocated_context(::std::string* context);

  // .eraftpb.Snapshot snapshot = 9;
  bool has_snapshot() const;
  void clear_snapshot();
  static const int kSnapshotFieldNumber = 9;
  private:
  const ::eraftpb::Snapshot& _internal_snapshot() const;
  public:
  const ::eraftpb::Snapshot& snapshot() const;
  ::eraftpb::Snapshot* release_snapshot();
  ::eraftpb::Snapshot* mutable_snapshot();
  void set_allocated_snapshot(::eraftpb::Snapshot* snapshot);

  // uint64 to = 2;
  void clear_to();
  static const int kToFieldNumber = 2;
  ::google::protobuf::uint64 to() const;
  void set_to(::google::protobuf::uint64 value);

  // uint64 from = 3;
  void clear_from();
  static const int kFromFieldNumber = 3;
  ::google::protobuf::uint64 from() const;
  void set_from(::google::protobuf::uint64 value);

  // uint64 term = 4;
  void clear_term();
  static const int kTermFieldNumber = 4;
  ::google::protobuf::uint64 term() const;
  void set_term(::google::protobuf::uint64 value);

  // uint64 log_term = 5;
  void clear_log_term();
  static const int kLogTermFieldNumber = 5;
  ::google::protobuf::uint64 log_term() const;
  void set_log_term(::google::protobuf::uint64 value);

  // .eraftpb.MessageType msg_type = 1;
  void clear_msg_type();
  static const int kMsgTypeFieldNumber = 1;
  ::eraftpb::MessageType msg_type() const;
  void set_msg_type(::eraftpb::MessageType value);

  // bool reject = 10;
  void clear_reject();
  static const int kRejectFieldNumber = 10;
  bool reject() const;
  void set_reject(bool value);

  // uint64 index = 6;
  void clear_index();
  static const int kIndexFieldNumber = 6;
  ::google::protobuf::uint64 index() const;
  void set_index(::google::protobuf::uint64 value);

  // uint64 commit = 8;
  void clear_commit();
  static const int kCommitFieldNumber = 8;
  ::google::protobuf::uint64 commit() const;
  void set_commit(::google::protobuf::uint64 value);

  // uint64 reject_hint = 11;
  void clear_reject_hint();
  static const int kRejectHintFieldNumber = 11;
  ::google::protobuf::uint64 reject_hint() const;
  void set_reject_hint(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:eraftpb.Message)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::eraftpb::Entry > entries_;
  ::google::protobuf::internal::ArenaStringPtr context_;
  ::eraftpb::Snapshot* snapshot_;
  ::google::protobuf::uint64 to_;
  ::google::protobuf::uint64 from_;
  ::google::protobuf::uint64 term_;
  ::google::protobuf::uint64 log_term_;
  int msg_type_;
  bool reject_;
  ::google::protobuf::uint64 index_;
  ::google::protobuf::uint64 commit_;
  ::google::protobuf::uint64 reject_hint_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_eraftpb_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class HardState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eraftpb.HardState) */ {
 public:
  HardState();
  virtual ~HardState();

  HardState(const HardState& from);

  inline HardState& operator=(const HardState& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  HardState(HardState&& from) noexcept
    : HardState() {
    *this = ::std::move(from);
  }

  inline HardState& operator=(HardState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const HardState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HardState* internal_default_instance() {
    return reinterpret_cast<const HardState*>(
               &_HardState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(HardState* other);
  friend void swap(HardState& a, HardState& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline HardState* New() const final {
    return CreateMaybeMessage<HardState>(NULL);
  }

  HardState* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<HardState>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const HardState& from);
  void MergeFrom(const HardState& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HardState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 term = 1;
  void clear_term();
  static const int kTermFieldNumber = 1;
  ::google::protobuf::uint64 term() const;
  void set_term(::google::protobuf::uint64 value);

  // uint64 vote = 2;
  void clear_vote();
  static const int kVoteFieldNumber = 2;
  ::google::protobuf::uint64 vote() const;
  void set_vote(::google::protobuf::uint64 value);

  // uint64 commit = 3;
  void clear_commit();
  static const int kCommitFieldNumber = 3;
  ::google::protobuf::uint64 commit() const;
  void set_commit(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:eraftpb.HardState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 term_;
  ::google::protobuf::uint64 vote_;
  ::google::protobuf::uint64 commit_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_eraftpb_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ConfState : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eraftpb.ConfState) */ {
 public:
  ConfState();
  virtual ~ConfState();

  ConfState(const ConfState& from);

  inline ConfState& operator=(const ConfState& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConfState(ConfState&& from) noexcept
    : ConfState() {
    *this = ::std::move(from);
  }

  inline ConfState& operator=(ConfState&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ConfState& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConfState* internal_default_instance() {
    return reinterpret_cast<const ConfState*>(
               &_ConfState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(ConfState* other);
  friend void swap(ConfState& a, ConfState& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConfState* New() const final {
    return CreateMaybeMessage<ConfState>(NULL);
  }

  ConfState* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ConfState>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ConfState& from);
  void MergeFrom(const ConfState& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConfState* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint64 nodes = 1;
  int nodes_size() const;
  void clear_nodes();
  static const int kNodesFieldNumber = 1;
  ::google::protobuf::uint64 nodes(int index) const;
  void set_nodes(int index, ::google::protobuf::uint64 value);
  void add_nodes(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      nodes() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_nodes();

  // repeated uint64 learners = 2;
  int learners_size() const;
  void clear_learners();
  static const int kLearnersFieldNumber = 2;
  ::google::protobuf::uint64 learners(int index) const;
  void set_learners(int index, ::google::protobuf::uint64 value);
  void add_learners(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      learners() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_learners();

  // @@protoc_insertion_point(class_scope:eraftpb.ConfState)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > nodes_;
  mutable int _nodes_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > learners_;
  mutable int _learners_cached_byte_size_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_eraftpb_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ConfChange : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:eraftpb.ConfChange) */ {
 public:
  ConfChange();
  virtual ~ConfChange();

  ConfChange(const ConfChange& from);

  inline ConfChange& operator=(const ConfChange& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConfChange(ConfChange&& from) noexcept
    : ConfChange() {
    *this = ::std::move(from);
  }

  inline ConfChange& operator=(ConfChange&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ConfChange& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConfChange* internal_default_instance() {
    return reinterpret_cast<const ConfChange*>(
               &_ConfChange_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(ConfChange* other);
  friend void swap(ConfChange& a, ConfChange& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConfChange* New() const final {
    return CreateMaybeMessage<ConfChange>(NULL);
  }

  ConfChange* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ConfChange>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ConfChange& from);
  void MergeFrom(const ConfChange& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConfChange* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes context = 4;
  void clear_context();
  static const int kContextFieldNumber = 4;
  const ::std::string& context() const;
  void set_context(const ::std::string& value);
  #if LANG_CXX11
  void set_context(::std::string&& value);
  #endif
  void set_context(const char* value);
  void set_context(const void* value, size_t size);
  ::std::string* mutable_context();
  ::std::string* release_context();
  void set_allocated_context(::std::string* context);

  // uint64 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint64 id() const;
  void set_id(::google::protobuf::uint64 value);

  // uint64 node_id = 3;
  void clear_node_id();
  static const int kNodeIdFieldNumber = 3;
  ::google::protobuf::uint64 node_id() const;
  void set_node_id(::google::protobuf::uint64 value);

  // .eraftpb.ConfChangeType change_type = 2;
  void clear_change_type();
  static const int kChangeTypeFieldNumber = 2;
  ::eraftpb::ConfChangeType change_type() const;
  void set_change_type(::eraftpb::ConfChangeType value);

  // @@protoc_insertion_point(class_scope:eraftpb.ConfChange)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr context_;
  ::google::protobuf::uint64 id_;
  ::google::protobuf::uint64 node_id_;
  int change_type_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_eraftpb_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Entry

// .eraftpb.EntryType entry_type = 1;
inline void Entry::clear_entry_type() {
  entry_type_ = 0;
}
inline ::eraftpb::EntryType Entry::entry_type() const {
  // @@protoc_insertion_point(field_get:eraftpb.Entry.entry_type)
  return static_cast< ::eraftpb::EntryType >(entry_type_);
}
inline void Entry::set_entry_type(::eraftpb::EntryType value) {
  
  entry_type_ = value;
  // @@protoc_insertion_point(field_set:eraftpb.Entry.entry_type)
}

// uint64 term = 2;
inline void Entry::clear_term() {
  term_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Entry::term() const {
  // @@protoc_insertion_point(field_get:eraftpb.Entry.term)
  return term_;
}
inline void Entry::set_term(::google::protobuf::uint64 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:eraftpb.Entry.term)
}

// uint64 index = 3;
inline void Entry::clear_index() {
  index_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Entry::index() const {
  // @@protoc_insertion_point(field_get:eraftpb.Entry.index)
  return index_;
}
inline void Entry::set_index(::google::protobuf::uint64 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:eraftpb.Entry.index)
}

// bytes data = 4;
inline void Entry::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Entry::data() const {
  // @@protoc_insertion_point(field_get:eraftpb.Entry.data)
  return data_.GetNoArena();
}
inline void Entry::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:eraftpb.Entry.data)
}
#if LANG_CXX11
inline void Entry::set_data(::std::string&& value) {
  
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:eraftpb.Entry.data)
}
#endif
inline void Entry::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:eraftpb.Entry.data)
}
inline void Entry::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:eraftpb.Entry.data)
}
inline ::std::string* Entry::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:eraftpb.Entry.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Entry::release_data() {
  // @@protoc_insertion_point(field_release:eraftpb.Entry.data)
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Entry::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:eraftpb.Entry.data)
}

// bytes context = 6;
inline void Entry::clear_context() {
  context_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Entry::context() const {
  // @@protoc_insertion_point(field_get:eraftpb.Entry.context)
  return context_.GetNoArena();
}
inline void Entry::set_context(const ::std::string& value) {
  
  context_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:eraftpb.Entry.context)
}
#if LANG_CXX11
inline void Entry::set_context(::std::string&& value) {
  
  context_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:eraftpb.Entry.context)
}
#endif
inline void Entry::set_context(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  context_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:eraftpb.Entry.context)
}
inline void Entry::set_context(const void* value, size_t size) {
  
  context_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:eraftpb.Entry.context)
}
inline ::std::string* Entry::mutable_context() {
  
  // @@protoc_insertion_point(field_mutable:eraftpb.Entry.context)
  return context_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Entry::release_context() {
  // @@protoc_insertion_point(field_release:eraftpb.Entry.context)
  
  return context_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Entry::set_allocated_context(::std::string* context) {
  if (context != NULL) {
    
  } else {
    
  }
  context_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), context);
  // @@protoc_insertion_point(field_set_allocated:eraftpb.Entry.context)
}

// bool sync_log = 5;
inline void Entry::clear_sync_log() {
  sync_log_ = false;
}
inline bool Entry::sync_log() const {
  // @@protoc_insertion_point(field_get:eraftpb.Entry.sync_log)
  return sync_log_;
}
inline void Entry::set_sync_log(bool value) {
  
  sync_log_ = value;
  // @@protoc_insertion_point(field_set:eraftpb.Entry.sync_log)
}

// -------------------------------------------------------------------

// SnapshotMetadata

// .eraftpb.ConfState conf_state = 1;
inline bool SnapshotMetadata::has_conf_state() const {
  return this != internal_default_instance() && conf_state_ != NULL;
}
inline void SnapshotMetadata::clear_conf_state() {
  if (GetArenaNoVirtual() == NULL && conf_state_ != NULL) {
    delete conf_state_;
  }
  conf_state_ = NULL;
}
inline const ::eraftpb::ConfState& SnapshotMetadata::_internal_conf_state() const {
  return *conf_state_;
}
inline const ::eraftpb::ConfState& SnapshotMetadata::conf_state() const {
  const ::eraftpb::ConfState* p = conf_state_;
  // @@protoc_insertion_point(field_get:eraftpb.SnapshotMetadata.conf_state)
  return p != NULL ? *p : *reinterpret_cast<const ::eraftpb::ConfState*>(
      &::eraftpb::_ConfState_default_instance_);
}
inline ::eraftpb::ConfState* SnapshotMetadata::release_conf_state() {
  // @@protoc_insertion_point(field_release:eraftpb.SnapshotMetadata.conf_state)
  
  ::eraftpb::ConfState* temp = conf_state_;
  conf_state_ = NULL;
  return temp;
}
inline ::eraftpb::ConfState* SnapshotMetadata::mutable_conf_state() {
  
  if (conf_state_ == NULL) {
    auto* p = CreateMaybeMessage<::eraftpb::ConfState>(GetArenaNoVirtual());
    conf_state_ = p;
  }
  // @@protoc_insertion_point(field_mutable:eraftpb.SnapshotMetadata.conf_state)
  return conf_state_;
}
inline void SnapshotMetadata::set_allocated_conf_state(::eraftpb::ConfState* conf_state) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete conf_state_;
  }
  if (conf_state) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      conf_state = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, conf_state, submessage_arena);
    }
    
  } else {
    
  }
  conf_state_ = conf_state;
  // @@protoc_insertion_point(field_set_allocated:eraftpb.SnapshotMetadata.conf_state)
}

// uint64 index = 2;
inline void SnapshotMetadata::clear_index() {
  index_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 SnapshotMetadata::index() const {
  // @@protoc_insertion_point(field_get:eraftpb.SnapshotMetadata.index)
  return index_;
}
inline void SnapshotMetadata::set_index(::google::protobuf::uint64 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:eraftpb.SnapshotMetadata.index)
}

// uint64 term = 3;
inline void SnapshotMetadata::clear_term() {
  term_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 SnapshotMetadata::term() const {
  // @@protoc_insertion_point(field_get:eraftpb.SnapshotMetadata.term)
  return term_;
}
inline void SnapshotMetadata::set_term(::google::protobuf::uint64 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:eraftpb.SnapshotMetadata.term)
}

// -------------------------------------------------------------------

// Snapshot

// bytes data = 1;
inline void Snapshot::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Snapshot::data() const {
  // @@protoc_insertion_point(field_get:eraftpb.Snapshot.data)
  return data_.GetNoArena();
}
inline void Snapshot::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:eraftpb.Snapshot.data)
}
#if LANG_CXX11
inline void Snapshot::set_data(::std::string&& value) {
  
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:eraftpb.Snapshot.data)
}
#endif
inline void Snapshot::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:eraftpb.Snapshot.data)
}
inline void Snapshot::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:eraftpb.Snapshot.data)
}
inline ::std::string* Snapshot::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:eraftpb.Snapshot.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Snapshot::release_data() {
  // @@protoc_insertion_point(field_release:eraftpb.Snapshot.data)
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Snapshot::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:eraftpb.Snapshot.data)
}

// .eraftpb.SnapshotMetadata metadata = 2;
inline bool Snapshot::has_metadata() const {
  return this != internal_default_instance() && metadata_ != NULL;
}
inline void Snapshot::clear_metadata() {
  if (GetArenaNoVirtual() == NULL && metadata_ != NULL) {
    delete metadata_;
  }
  metadata_ = NULL;
}
inline const ::eraftpb::SnapshotMetadata& Snapshot::_internal_metadata() const {
  return *metadata_;
}
inline const ::eraftpb::SnapshotMetadata& Snapshot::metadata() const {
  const ::eraftpb::SnapshotMetadata* p = metadata_;
  // @@protoc_insertion_point(field_get:eraftpb.Snapshot.metadata)
  return p != NULL ? *p : *reinterpret_cast<const ::eraftpb::SnapshotMetadata*>(
      &::eraftpb::_SnapshotMetadata_default_instance_);
}
inline ::eraftpb::SnapshotMetadata* Snapshot::release_metadata() {
  // @@protoc_insertion_point(field_release:eraftpb.Snapshot.metadata)
  
  ::eraftpb::SnapshotMetadata* temp = metadata_;
  metadata_ = NULL;
  return temp;
}
inline ::eraftpb::SnapshotMetadata* Snapshot::mutable_metadata() {
  
  if (metadata_ == NULL) {
    auto* p = CreateMaybeMessage<::eraftpb::SnapshotMetadata>(GetArenaNoVirtual());
    metadata_ = p;
  }
  // @@protoc_insertion_point(field_mutable:eraftpb.Snapshot.metadata)
  return metadata_;
}
inline void Snapshot::set_allocated_metadata(::eraftpb::SnapshotMetadata* metadata) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete metadata_;
  }
  if (metadata) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      metadata = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, metadata, submessage_arena);
    }
    
  } else {
    
  }
  metadata_ = metadata;
  // @@protoc_insertion_point(field_set_allocated:eraftpb.Snapshot.metadata)
}

// -------------------------------------------------------------------

// Message

// .eraftpb.MessageType msg_type = 1;
inline void Message::clear_msg_type() {
  msg_type_ = 0;
}
inline ::eraftpb::MessageType Message::msg_type() const {
  // @@protoc_insertion_point(field_get:eraftpb.Message.msg_type)
  return static_cast< ::eraftpb::MessageType >(msg_type_);
}
inline void Message::set_msg_type(::eraftpb::MessageType value) {
  
  msg_type_ = value;
  // @@protoc_insertion_point(field_set:eraftpb.Message.msg_type)
}

// uint64 to = 2;
inline void Message::clear_to() {
  to_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Message::to() const {
  // @@protoc_insertion_point(field_get:eraftpb.Message.to)
  return to_;
}
inline void Message::set_to(::google::protobuf::uint64 value) {
  
  to_ = value;
  // @@protoc_insertion_point(field_set:eraftpb.Message.to)
}

// uint64 from = 3;
inline void Message::clear_from() {
  from_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Message::from() const {
  // @@protoc_insertion_point(field_get:eraftpb.Message.from)
  return from_;
}
inline void Message::set_from(::google::protobuf::uint64 value) {
  
  from_ = value;
  // @@protoc_insertion_point(field_set:eraftpb.Message.from)
}

// uint64 term = 4;
inline void Message::clear_term() {
  term_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Message::term() const {
  // @@protoc_insertion_point(field_get:eraftpb.Message.term)
  return term_;
}
inline void Message::set_term(::google::protobuf::uint64 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:eraftpb.Message.term)
}

// uint64 log_term = 5;
inline void Message::clear_log_term() {
  log_term_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Message::log_term() const {
  // @@protoc_insertion_point(field_get:eraftpb.Message.log_term)
  return log_term_;
}
inline void Message::set_log_term(::google::protobuf::uint64 value) {
  
  log_term_ = value;
  // @@protoc_insertion_point(field_set:eraftpb.Message.log_term)
}

// uint64 index = 6;
inline void Message::clear_index() {
  index_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Message::index() const {
  // @@protoc_insertion_point(field_get:eraftpb.Message.index)
  return index_;
}
inline void Message::set_index(::google::protobuf::uint64 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:eraftpb.Message.index)
}

// repeated .eraftpb.Entry entries = 7;
inline int Message::entries_size() const {
  return entries_.size();
}
inline void Message::clear_entries() {
  entries_.Clear();
}
inline ::eraftpb::Entry* Message::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:eraftpb.Message.entries)
  return entries_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::eraftpb::Entry >*
Message::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:eraftpb.Message.entries)
  return &entries_;
}
inline const ::eraftpb::Entry& Message::entries(int index) const {
  // @@protoc_insertion_point(field_get:eraftpb.Message.entries)
  return entries_.Get(index);
}
inline ::eraftpb::Entry* Message::add_entries() {
  // @@protoc_insertion_point(field_add:eraftpb.Message.entries)
  return entries_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::eraftpb::Entry >&
Message::entries() const {
  // @@protoc_insertion_point(field_list:eraftpb.Message.entries)
  return entries_;
}

// uint64 commit = 8;
inline void Message::clear_commit() {
  commit_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Message::commit() const {
  // @@protoc_insertion_point(field_get:eraftpb.Message.commit)
  return commit_;
}
inline void Message::set_commit(::google::protobuf::uint64 value) {
  
  commit_ = value;
  // @@protoc_insertion_point(field_set:eraftpb.Message.commit)
}

// .eraftpb.Snapshot snapshot = 9;
inline bool Message::has_snapshot() const {
  return this != internal_default_instance() && snapshot_ != NULL;
}
inline void Message::clear_snapshot() {
  if (GetArenaNoVirtual() == NULL && snapshot_ != NULL) {
    delete snapshot_;
  }
  snapshot_ = NULL;
}
inline const ::eraftpb::Snapshot& Message::_internal_snapshot() const {
  return *snapshot_;
}
inline const ::eraftpb::Snapshot& Message::snapshot() const {
  const ::eraftpb::Snapshot* p = snapshot_;
  // @@protoc_insertion_point(field_get:eraftpb.Message.snapshot)
  return p != NULL ? *p : *reinterpret_cast<const ::eraftpb::Snapshot*>(
      &::eraftpb::_Snapshot_default_instance_);
}
inline ::eraftpb::Snapshot* Message::release_snapshot() {
  // @@protoc_insertion_point(field_release:eraftpb.Message.snapshot)
  
  ::eraftpb::Snapshot* temp = snapshot_;
  snapshot_ = NULL;
  return temp;
}
inline ::eraftpb::Snapshot* Message::mutable_snapshot() {
  
  if (snapshot_ == NULL) {
    auto* p = CreateMaybeMessage<::eraftpb::Snapshot>(GetArenaNoVirtual());
    snapshot_ = p;
  }
  // @@protoc_insertion_point(field_mutable:eraftpb.Message.snapshot)
  return snapshot_;
}
inline void Message::set_allocated_snapshot(::eraftpb::Snapshot* snapshot) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete snapshot_;
  }
  if (snapshot) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      snapshot = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, snapshot, submessage_arena);
    }
    
  } else {
    
  }
  snapshot_ = snapshot;
  // @@protoc_insertion_point(field_set_allocated:eraftpb.Message.snapshot)
}

// bool reject = 10;
inline void Message::clear_reject() {
  reject_ = false;
}
inline bool Message::reject() const {
  // @@protoc_insertion_point(field_get:eraftpb.Message.reject)
  return reject_;
}
inline void Message::set_reject(bool value) {
  
  reject_ = value;
  // @@protoc_insertion_point(field_set:eraftpb.Message.reject)
}

// uint64 reject_hint = 11;
inline void Message::clear_reject_hint() {
  reject_hint_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Message::reject_hint() const {
  // @@protoc_insertion_point(field_get:eraftpb.Message.reject_hint)
  return reject_hint_;
}
inline void Message::set_reject_hint(::google::protobuf::uint64 value) {
  
  reject_hint_ = value;
  // @@protoc_insertion_point(field_set:eraftpb.Message.reject_hint)
}

// bytes context = 12;
inline void Message::clear_context() {
  context_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Message::context() const {
  // @@protoc_insertion_point(field_get:eraftpb.Message.context)
  return context_.GetNoArena();
}
inline void Message::set_context(const ::std::string& value) {
  
  context_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:eraftpb.Message.context)
}
#if LANG_CXX11
inline void Message::set_context(::std::string&& value) {
  
  context_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:eraftpb.Message.context)
}
#endif
inline void Message::set_context(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  context_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:eraftpb.Message.context)
}
inline void Message::set_context(const void* value, size_t size) {
  
  context_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:eraftpb.Message.context)
}
inline ::std::string* Message::mutable_context() {
  
  // @@protoc_insertion_point(field_mutable:eraftpb.Message.context)
  return context_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Message::release_context() {
  // @@protoc_insertion_point(field_release:eraftpb.Message.context)
  
  return context_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Message::set_allocated_context(::std::string* context) {
  if (context != NULL) {
    
  } else {
    
  }
  context_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), context);
  // @@protoc_insertion_point(field_set_allocated:eraftpb.Message.context)
}

// -------------------------------------------------------------------

// HardState

// uint64 term = 1;
inline void HardState::clear_term() {
  term_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 HardState::term() const {
  // @@protoc_insertion_point(field_get:eraftpb.HardState.term)
  return term_;
}
inline void HardState::set_term(::google::protobuf::uint64 value) {
  
  term_ = value;
  // @@protoc_insertion_point(field_set:eraftpb.HardState.term)
}

// uint64 vote = 2;
inline void HardState::clear_vote() {
  vote_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 HardState::vote() const {
  // @@protoc_insertion_point(field_get:eraftpb.HardState.vote)
  return vote_;
}
inline void HardState::set_vote(::google::protobuf::uint64 value) {
  
  vote_ = value;
  // @@protoc_insertion_point(field_set:eraftpb.HardState.vote)
}

// uint64 commit = 3;
inline void HardState::clear_commit() {
  commit_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 HardState::commit() const {
  // @@protoc_insertion_point(field_get:eraftpb.HardState.commit)
  return commit_;
}
inline void HardState::set_commit(::google::protobuf::uint64 value) {
  
  commit_ = value;
  // @@protoc_insertion_point(field_set:eraftpb.HardState.commit)
}

// -------------------------------------------------------------------

// ConfState

// repeated uint64 nodes = 1;
inline int ConfState::nodes_size() const {
  return nodes_.size();
}
inline void ConfState::clear_nodes() {
  nodes_.Clear();
}
inline ::google::protobuf::uint64 ConfState::nodes(int index) const {
  // @@protoc_insertion_point(field_get:eraftpb.ConfState.nodes)
  return nodes_.Get(index);
}
inline void ConfState::set_nodes(int index, ::google::protobuf::uint64 value) {
  nodes_.Set(index, value);
  // @@protoc_insertion_point(field_set:eraftpb.ConfState.nodes)
}
inline void ConfState::add_nodes(::google::protobuf::uint64 value) {
  nodes_.Add(value);
  // @@protoc_insertion_point(field_add:eraftpb.ConfState.nodes)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
ConfState::nodes() const {
  // @@protoc_insertion_point(field_list:eraftpb.ConfState.nodes)
  return nodes_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
ConfState::mutable_nodes() {
  // @@protoc_insertion_point(field_mutable_list:eraftpb.ConfState.nodes)
  return &nodes_;
}

// repeated uint64 learners = 2;
inline int ConfState::learners_size() const {
  return learners_.size();
}
inline void ConfState::clear_learners() {
  learners_.Clear();
}
inline ::google::protobuf::uint64 ConfState::learners(int index) const {
  // @@protoc_insertion_point(field_get:eraftpb.ConfState.learners)
  return learners_.Get(index);
}
inline void ConfState::set_learners(int index, ::google::protobuf::uint64 value) {
  learners_.Set(index, value);
  // @@protoc_insertion_point(field_set:eraftpb.ConfState.learners)
}
inline void ConfState::add_learners(::google::protobuf::uint64 value) {
  learners_.Add(value);
  // @@protoc_insertion_point(field_add:eraftpb.ConfState.learners)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
ConfState::learners() const {
  // @@protoc_insertion_point(field_list:eraftpb.ConfState.learners)
  return learners_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
ConfState::mutable_learners() {
  // @@protoc_insertion_point(field_mutable_list:eraftpb.ConfState.learners)
  return &learners_;
}

// -------------------------------------------------------------------

// ConfChange

// uint64 id = 1;
inline void ConfChange::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ConfChange::id() const {
  // @@protoc_insertion_point(field_get:eraftpb.ConfChange.id)
  return id_;
}
inline void ConfChange::set_id(::google::protobuf::uint64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:eraftpb.ConfChange.id)
}

// .eraftpb.ConfChangeType change_type = 2;
inline void ConfChange::clear_change_type() {
  change_type_ = 0;
}
inline ::eraftpb::ConfChangeType ConfChange::change_type() const {
  // @@protoc_insertion_point(field_get:eraftpb.ConfChange.change_type)
  return static_cast< ::eraftpb::ConfChangeType >(change_type_);
}
inline void ConfChange::set_change_type(::eraftpb::ConfChangeType value) {
  
  change_type_ = value;
  // @@protoc_insertion_point(field_set:eraftpb.ConfChange.change_type)
}

// uint64 node_id = 3;
inline void ConfChange::clear_node_id() {
  node_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ConfChange::node_id() const {
  // @@protoc_insertion_point(field_get:eraftpb.ConfChange.node_id)
  return node_id_;
}
inline void ConfChange::set_node_id(::google::protobuf::uint64 value) {
  
  node_id_ = value;
  // @@protoc_insertion_point(field_set:eraftpb.ConfChange.node_id)
}

// bytes context = 4;
inline void ConfChange::clear_context() {
  context_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ConfChange::context() const {
  // @@protoc_insertion_point(field_get:eraftpb.ConfChange.context)
  return context_.GetNoArena();
}
inline void ConfChange::set_context(const ::std::string& value) {
  
  context_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:eraftpb.ConfChange.context)
}
#if LANG_CXX11
inline void ConfChange::set_context(::std::string&& value) {
  
  context_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:eraftpb.ConfChange.context)
}
#endif
inline void ConfChange::set_context(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  context_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:eraftpb.ConfChange.context)
}
inline void ConfChange::set_context(const void* value, size_t size) {
  
  context_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:eraftpb.ConfChange.context)
}
inline ::std::string* ConfChange::mutable_context() {
  
  // @@protoc_insertion_point(field_mutable:eraftpb.ConfChange.context)
  return context_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ConfChange::release_context() {
  // @@protoc_insertion_point(field_release:eraftpb.ConfChange.context)
  
  return context_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConfChange::set_allocated_context(::std::string* context) {
  if (context != NULL) {
    
  } else {
    
  }
  context_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), context);
  // @@protoc_insertion_point(field_set_allocated:eraftpb.ConfChange.context)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace eraftpb

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::eraftpb::EntryType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::eraftpb::EntryType>() {
  return ::eraftpb::EntryType_descriptor();
}
template <> struct is_proto_enum< ::eraftpb::MessageType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::eraftpb::MessageType>() {
  return ::eraftpb::MessageType_descriptor();
}
template <> struct is_proto_enum< ::eraftpb::ConfChangeType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::eraftpb::ConfChangeType>() {
  return ::eraftpb::ConfChangeType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_eraftpb_2eproto
